# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-112060364-2'

menu:
- {name: '讲道录音', folder: 'pages', file: 'documentation.html'}
- {name: '关于我们', folder: 'pages', file: 'about.html'}
- {name: '联系我们', folder: 'pages', file: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'facebook', link: 'https://www.facebook.com/%E5%8D%8E%E5%A4%8F%E5%9C%A3%E7%BB%8F%E6%95%99%E4%BC%9A%E8%A5%BF%E5%A0%82wtcbc-111202637167983'}
- {icon: 'envelope', link: 'mailto:info@wtcbc.com'}
- {icon: 'rss-square', link: 'feed.xml'}

# Customize site text
pagination:
  next_page: '下一页'
  previous_page: '上一页'

sharing_button_prompt: '自由分享这个消息吧！'

related_posts: '您可能喜欢...'

post_date_prefix: '写于'
